repository :first, 'http://bld200/nexus/content/repositories/vmc-vendor'
jar 'org.slf4j:slf4j-api', '1.6.4'
jar 'com.github.sgroschupf:zkclient', '0.1'
jar 'org.apache.zookeeper:zookeeper', '3.3.4'
jar 'log4j:log4j', '1.2.17'
jar 'org.scala-lang:scala-library', '2.8.0'
jar 'net.sf.jopt-simple:jopt-simple', '3.2'
jar 'com.visiblemeasures.kafka:kafka', '0.7.2'
